author = Artur Tarassow and Allin Cottrell
email = atecon@posteo.de
version = @VERSION@
date = 2026-06-11
description = Scatterplot matrix with factor separation
tags = C88
min-version = @VERSION@
gui-main = GUI_PairPlot
ui-maker = PP_ui_maker
label = Pair Plot
menu-attachment = MAINWIN/View/GraphVars
public = PairPlot GUI_PairPlot
no-print = GUI_PairPlot
help = PairPlot_help.md
sample-script = PairPlot_sample.inp
