.TH "gretl" "1" "1.9.5" "The gretl team" "econometrics"
.SH "NAME"
gretl \- GNU Regression, Econometrics and Time\-series Library

.SH "SYNOPSIS"
\fBgretl\fR [ options ] [ \fIdatafile\fP | \fIscriptfile\fP | \fIsessionfile\fP ]
.br 

.SH "DESCRIPTION"
gretl is an econometrics package, built around a shared
library which may be accessed using a command\-line client
program (\fBgretlcli\fR) or a graphical user interface
(\fBgretl_x11\fR).  The program \fBgretl\fR is a wrapper script that
calls the GUI if the DISPLAY environment variable is set, otherwise
the command\-line client.  

For details, please start up either the GUI or the
command\-line client and consult the online help, or read the
printed manual, which is available in PDF format via the
gretl website, \fBhttp://gretl.sourceforge.net\fR.

.SH "OPTIONS"
These are the options supported by the \fBgretl_x11\fR program;
\fBgretlcli\fR is a little different.
.TP
\fB\-r\fR script, \fB\-\-run\fR script

Open a script.
.TP
\fB\-c\fR, \fB\-\-dump\fR

Dump the configuration file.
.TP
\fB\-d\fR database, \fB\-\-db\fR database

Open a local database.
.TP
\fB\-e\fR, \fB\-\-english\fR

Force use of English.
.TP
\fB\-r\fR script, \fB\-\-run\fR script

Open a script.
.TP
\fB\-w\fR database, \fB\-\-webdb\fR database

Open a remote database.
.TP
\fB\-h\fR, \fB\-\-help\fR

Give help information and exit.
.TP 
\fB\-v\fR, \fB\-\-version\fR

Give version information and exit.

.SH "FILES"
\fI~/.gretl2rc\fP per\-user configuration file
.TP
\fI~/.gretl\fP directory for user runtime files

.SH "ENVIRONMENT VARIABLES"
.TP 
\fBHOME\fP
Specifies the user's home directory
.TP 
\fBDISPLAY\fP
Specifies the X window display to use

.SH "SEE ALSO"
\fBgretlcli\fR(1)

.SH "AUTHOR"
The gretl team
