.\" Man page contributed by Dirk Eddelbuettel <edd@debian.org>
.\" and released under the GNU General Public License
.TH GRETL-CONFIG 1 "27 August 2001" GNU
.SH NAME
gretl-config - compiler / linker flags for Gretl libs
.SH SYNOPSIS
.B gretl-config
[\-\-prefix[=DIR]]  [\-\-exec-prefix[=DIR]]  [\-\-version] [\-\-libs] [\-\-cflags]
.SH DESCRIPTION
\fIgretl-config\fP is a tool which can be used to determine
the compiler and linker flags that should be used to compile
and link programs that use \fIGretl\fP. 
.SH OPTIONS
\fIgretl-config\fP accepts the following options:
.TP 8
.B  \-\-prefix[=DIR]
Show the Gretl installation prefix.
.TP 8
.B  \-\-exec-prefix[=DIR]
Show the Gretl execution direction prefix.
.TP 8
.B  \-\-libs
Print the linker flags that are necessary to link a \fIGretl\fP program.
.TP 8
.B  \-\-cflags
Print the compiler flags that are necessary to compile a \fIGretl\fP program.
.TP 8
.B  \-\-version
Print the currently installed version of \fIGretl\fP on the standard output.
.SH SEE ALSO
.BR gretl (1),
.BR gtk-config (1),
.BR gnome-config (1),
.B gretl
documentation and website
.BR http://www.ecn.wfu.edu/gretl. 
.SH AUTHOR
Allin Cottrell <cottrell@wfu.edu>     

This manual page was added by the Dirk Eddelbuettel
<edd@debian.org>, the Debian GNU/Linux maintainer for 
.BR gretl .
