CC = gcc
LIBS = -lf2c -lm
GLIB_CFLAGS = `pkg-config --cflags glib-2.0`
GLIB_LIBS = `pkg-config --libs glib-2.0`

all: diehard mtrand

diehard: diehard.c
	$(CC) -o $@ $< $(LIBS)

mtrand: mtrand.c
	$(CC) -o $@ $< $(GLIB_CFLAGS) $(GLIB_LIBS)

clean:
	rm -f diehard mtrand gretl.32 gretl_rand.txt
