author = Artur Tarassow
email = atecon@posteo.de
version = 0.2
date = 2021-06-18
description = Record the history of a computation as a log of events.
tags = C81
min-version = 2018a
data-requirement = no-data-ok
min-version = 2021c
public = Debug Info Warn Error Critical
help = logging_help.txt
sample-script = logging_sample.inp
