author = Artur Tarassow
email = atecon@posteo.de
version = @VERSION@
date = 2021-07-08
description = Structured logging for script execution
tags = C81
data-requirement = no-data-ok
min-version = @VERSION@
public = Debug Info Warn Error Critical
help = logging.pdf
sample-script = logging_sample.inp
