#!/bin/sh

SRCDIR=/home/cottrell/stats/esl/gretl
TEMPLDIR=$SRCDIR/doc/website/template

newver=$1

if [ "x$newver" = "x" ]
then
   echo Usage: $0: new_version_number
   exit 1
fi

cp $SRCDIR/ChangeLog .
cp $SRCDIR/doc/manual.pdf .
cp $SRCDIR/doc/manual-a4.pdf .

newlong=`date`
newshort=`date +"%b %e, %Y"`

newlong_es=`LANG=es_ES date`
newshort_es=`LANG=es_ES date +"%b %e, %Y"`

newlong_it=`LANG=it_IT date`
newshort_it=`LANG=it_IT date +"%e %b %Y"`

cat $TEMPLDIR/index_pat.html | sed s/VERSION/${newver}/g \
  | sed s/LONGDATE/"${newlong}"/ | sed s/SHORTDATE/"${newshort}"/ > htmltmp
mv htmltmp index.html

cat $TEMPLDIR/gretl_espanol_pat.html | sed s/VERSION/${newver}/g \
  | sed s/LONGDATE/"${newlong_es}"/ | sed s/SHORTDATE/"${newshort_es}"/ > htmltmp
mv htmltmp gretl_espanol.html

cat $TEMPLDIR/gretl_italiano_pat.html | sed s/VERSION/${newver}/g \
  | sed s/LONGDATE/"${newlong_it}"/ | sed s/SHORTDATE/"${newshort_it}"/ > htmltmp
mv htmltmp gretl_italiano.html

cat $TEMPLDIR/win32_pat.html | sed s/SHORTDATE/"${newshort}"/ > htmltmp
mv htmltmp win32/index.html

cat $TEMPLDIR/win32_pat_es.html | sed s/SHORTDATE/"${newshort_es}"/ > htmltmp
mv htmltmp win32/index_es.html

cat $TEMPLDIR/win32_pat_it.html | sed s/SHORTDATE/"${newshort_it}"/ > htmltmp
mv htmltmp win32/index_it.html

cat $TEMPLDIR/osx_pat.html | sed s/VERSION/${newver}/g > htmltmp
mv htmltmp osx.html

cat $TEMPLDIR/osx_pat_es.html | sed s/VERSION/${newver}/g > htmltmp
mv htmltmp osx_es.html

cat $TEMPLDIR/osx_pat_it.html | sed s/VERSION/${newver}/g > htmltmp
mv htmltmp osx_it.html

cat $TEMPLDIR/changelog.top > htmltmp
cat ChangeLog >> htmltmp
cat $TEMPLDIR/changelog.end >> htmltmp
mv htmltmp ChangeLog.html
   

