#!/bin/sh

SRCDIR=/home/cottrell/stats/esl/gretl

newver=$1

if [ "x$newver" = "x" ]
then
   echo Usage: $0: new_version_number
   exit 1
fi

cp $SRCDIR/ChangeLog .
cp $SRCDIR/doc/manual.pdf .
cp $SRCDIR/doc/manual-a4.pdf .

newlong=`date`
newshort=`date +"%b %e, %Y"`

newlong_es=`LANG=spanish date`
newshort_es=`LANG=spanish date +"%b %e, %Y"`

cat template/index_pat.html | sed s/VERSION/${newver}/g \
  | sed s/LONGDATE/"${newlong}"/ | sed s/SHORTDATE/"${newshort}"/ > htmltmp
mv htmltmp index.html

cat template/gretl_espanol_pat.html | sed s/VERSION/${newver}/g \
  | sed s/LONGDATE/"${newlong_es}"/ | sed s/SHORTDATE/"${newshort_es}"/ > htmltmp
mv htmltmp gretl_espanol.html

cat template/win32_pat.html | sed s/SHORTDATE/"${newshort}"/ > htmltmp
mv htmltmp win32/index.html

cat template/win32_pat_es.html | sed s/SHORTDATE/"${newshort_es}"/ > htmltmp
mv htmltmp win32/index_es.html

cat template/osx_pat.html | sed s/VERSION/${newver}/g > htmltmp
mv htmltmp osx.html

cat template/osx_pat_es.html | sed s/VERSION/${newver}/g > htmltmp
mv htmltmp osx_es.html

cat template/changelog.top > htmltmp
cat ChangeLog >> htmltmp
cat template/changelog.end >> htmltmp
mv htmltmp ChangeLog.html
   

