author = Allin Cottrell
email = cottrell@wfu.edu
version = 0.4
date = 2011-02-10
description = Within and Between TSLS models plus G2SLS
public = ivpanel ivp_print GUI_ivpanel
gui-main = GUI_ivpanel
bundle-print = ivp_print
help = ivpanel.help
sample-script = examples/nc_crime.inp
min-version = 1.9.3
data-requirement = needs-panel-data
