#!/bin/sh

PLUG=$1
DEST=~/dist/Gretl_Folder/lib/gretl-gtk2

if [ "x$PLUG" = "x" ] ; then
  echo "Supply the basename of a plugin to install"
  exit 1;
fi

make ${PLUG}.la
../libtool --mode=install install -c -m 755 ${PLUG}.la $DEST


