pdf: manual.tex
	pdflatex manual
	pdflatex manual
	pdflatex manual

html: manual.tex
	latex manual
	latex manual
	l2h manual

dvi: manual.tex
	latex manual
	latex manual

clean:
	rm -f *.dvi *.aux *.toc *.out *.html *.log *.pdf
