#! /bin/sh

EMACS=`which emacs`
EPREFIX=`dirname $EMACS`
SITELISP=`echo $EPREFIX | sed s+bin+share+`/emacs/site-lisp

emacs -batch -f batch-byte-compile gretl.el &&
echo "Installing to $SITELISP"
sudo install -m 644 gretl.elc $SITELISP

