author = Allin Cottrell and Riccardo "Jack" Lucchetti
email = cottrell@wfu.edu
tags = C81 C88
version = 0.1
date = 2020-04-29
description = geospatial plotting
public = describe_geojson
help = geoplot.pdf
sample-script = geoplot_sample.inp
min-version = 2020c
data-requirement = no-data-ok
data-files = examples
