# Makefile for compiling Linux test version of win32 gretl_updater

CC = gcc -g -O2 -Wall
CFLAGS = -I../../lib/src -I../../win32/updater
SRC = update_client.c webget.c untgz.c
OBJ = update_client.o untgz.o

LIBS = -L/usr/local/lib -lz 

vpath %.h ../../lib/src ../../win32/updater
vpath %.c ../../lib/src ../../win32/updater

gretl_updater: $(OBJ) version.h
	 $(CC) -o $@ $(OBJ) $(LIBS)

update_client.o: update_client.c gretl_www.c

untgz.o: untgz.c


.PHONY :

clean:
	rm -f *.o gretl_updater


