#!/bin/sh

# Clean out unwanted files and add a few extra things.
# Run this in the gretl build directory

# The directory above Gretl.app
TOPDIR=/Users/allin/dist

PREFIX=$TOPDIR/Gretl.app/Contents/Resources

rm -f $PREFIX/bin/gretl
rm -rf $PREFIX/include
rm -rf $PREFIX/share/aclocal
rm -rf $PREFIX/share/info
rm -rf $PREFIX/info
rm -rf $PREFIX/lib/pkgconfig
rm -f $PREFIX/lib/*.la
rm -f $PREFIX/lib/gretl-gtk2/*.la
rm -rf $PREFIX/share/emacs
rm -rf $PREFIX/share/texmf-local

install -m 644 osx/README.pdf $TOPDIR
install -m 755 osx/gretl.sh $PREFIX/bin/gretl
install -m 755 osx/script $PREFIX
