#!/bin/sh
#
# Author: Aaron Voisine <aaron@voisine.org>

CWD="`dirname \"$0\"`"
echo "CWD=$CWD"

OSXVERSION=`/usr/bin/sw_vers | grep ProductVersion | cut -f2 -d'.'`

if [ "$OSXVERSION" -lt "5" ]; then
  ps -wx -ocommand | grep -e '[X]11' > /dev/null
  if [ "$?" != "0" -a ! -f ~/.xinitrc ]; then
    echo "rm -f ~/.xinitrc" > ~/.xinitrc
    sed 's/xterm/# xterm/' /usr/X11R6/lib/X11/xinit/xinitrc >> ~/.xinitrc
  fi

  cp -f "$CWD/bin/getdisplay.sh" /tmp/
  rm -f /tmp/display.$UID
  open-x11 /tmp/getdisplay.sh || \
  open -a XDarwin /tmp/getdisplay.sh || \
  echo ":0" > /tmp/display.$UID

  while [ "$?" == "0" -a ! -f /tmp/display.$UID ]; do
    sleep 1
  done
  export "DISPLAY=`cat /tmp/display.$UID`"

  ps -wx -ocommand | grep -e '[X]11' > /dev/null || exit 11
fi  

exec "$CWD/bin/gretl" "$@"

