#!/bin/sh

WWW='allin@gretl.sourceforge.net:~/www/'
topdir=/home/cottrell/stats/esl/gretl
version=$(cat lib/src/version.h | grep version_ | \
     awk '{ print $NF}' | sed s/[\"\;]//g)
tarfile="gretl-${version}.tar.gz"

echo "making dist file for gretl $version using filename $tarfile"

if [ -f ${topdir}/Makefile ] ; then
  cd ${topdir} && make distclean
fi  
cd ${topdir}/..
mkdir ${topdir}/../gretl-$version
date > gretl/share/gretl.stamp
cp -ap gretl/* gretl-$version
find gretl-$version -name "*CVS" | xargs rm -rf
find gretl-$version -name ".xvpics" | xargs rm -rf
rm -f gretl-$version/doc/*.aux gretl-$version/doc/*.log \
    gretl-$version/doc/*.toc gretl-$version/doc/*.tpt \
    gretl-$version/doc/*.out gretl-$version/doc/*.ced 
rm -rf gretl-$version/doc/gretlhlp gretl-$version/doc/reference \
    gretl-$version/doc/nist
tar cvfz $tarfile gretl-$version
rm -rf gretl-$version

scp gretl/doc/manual.pdf $WWW
scp gretl/doc/manual-a4.pdf $WWW
scp gretl/ChangeLog $WWW
