#!/bin/sh

TOPSRC=$1
BUILDDIR=`pwd`

cd ${TOPSRC}/gui && \
for f in \
  gretltypes.h \
  boxplots.c boxplots.h \
  calculator.c guiprint_common.c \
  callbacks.c callbacks.h \
  console.c console.h \
  database.c database.h \
  datafiles.c datafiles.h \
  fileselect.c \
  gpt_control.c gpt_control.h \
  gui_utils.c gui_utils.h \
  helpfiles.c helpfiles.h \
  model_table.c model_table.h \
  objectsave.c objectsave.h \
  series_view.c series_view.h \
  session.c session.h \
  settings.c settings.h \
  webget.c webget.h \
  library.c library.h ; do
    rm -f $f
    ln -s ${TOPSRC}/gui2/$f $f
done
cd $BUILDDIR

