#!/bin/sh

GRETLCLI="$1"

export GRETL_INCLUDE_PATH=`pwd`

rm -f test.out

for f in examples/*.inp ; do
  if $GRETLCLI -b $f >> test.out ; then 
     echo "$f: OK"
  else
     echo "$f: failed"
     break
  fi
done
