#!/bin/sh

GRETLCLI="$1"

export GRETL_INCLUDE_PATH=`pwd`

rm -f test.out

for f in *.inp ; do
  if [ "x$f" != "xpkg.inp" ] ; then
    if $GRETLCLI -b $f >> test.out ; then 
       echo "$f: OK"
    else
       echo "$f: failed"
       break
    fi
  fi
done

if [ -d examples ] ; then
  for f in `find examples/ -name "*.inp"` ; do
    if $GRETLCLI -b $f >> test.out ; then 
       echo "$f: OK"
    else
       echo "$f: failed"
       break
    fi
  done
fi
