author = Riccardo "Jack" Lucchetti
email = r.lucchetti@univpm.it
version = 1.0
date = 2022-01-15
description = Kalman Filter GUI
tags = C32
min-version = 2022a
public = KFgui KFgui_plot KFgui_print
help = KFgui.txt
sample-script = KFgui_sample.inp
gui-main = KFgui
bundle-print = KFgui_print
bundle-plot = KFgui_plot
data-files = examples
